spring:
  application:
    name: auth-server
  datasource:
    url: jdbc:mysql://localhost:3306/auth?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: dd@2018
    driverClassName: com.mysql.jdbc.Driver
    dbcp2:
      max-idle: 5
      max-wait-millis: 10000
      min-idle: 2
      initial-size: 3
      validation-query: SELECT 1
      time-between-eviction-runs-millis: 18800
    tomcat:
      jdbc-interceptors: ConnectionState;SlowQueryReport(threshold=50)

server:
  port: 8761
eureka:
  server:
    enable-self-preservation: false
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/ #服务注册中心地址
  instance:
    hostname: localhost