spring:
  application:
    name: auth-client
  datasource:
    url: jdbc:mysql://localhost:3306/auth?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: dd@2018
    driverClassName: com.mysql.jdbc.Driver
    dbcp2:
      max-idle: 5
      max-wait-millis: 10000
      min-idle: 2
      initial-size: 3
      validation-query: SELECT 1
      time-between-eviction-runs-millis: 18800
    tomcat:
      jdbc-interceptors: ConnectionState;SlowQueryReport(threshold=50)
  redis:
    database: 0
    host: localhost
    password:
    timeout: 3000
    jedis:
      pool:
        max-active: 5
        min-idle: 0
        max-wait: 1
        max-idle: 8
    port: 6379
server:
  port: 8760
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/ #服务注册中心地址
  instance:
    hostname: localhost